
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos Sanabria
 */
public class JF_Lab5P2_CarlosSanabria extends javax.swing.JFrame {

    /**
     * Creates new form JF_Lab5P2_CarlosSanabria
     */
    public JF_Lab5P2_CarlosSanabria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Juga = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_Nombre = new javax.swing.JTextField();
        TF_Apellido = new javax.swing.JTextField();
        TF_Nacionalidad = new javax.swing.JTextField();
        JS_Edad = new javax.swing.JSpinner();
        TF_Num_J = new javax.swing.JTextField();
        TF_Contrato = new javax.swing.JTextField();
        JB_AgregarJ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_Jugadores = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        JL_JUGA = new javax.swing.JList<>();
        JB_AJ = new javax.swing.JButton();
        JD_Entrenadores = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TF_Nombre1 = new javax.swing.JTextField();
        TF_Apellido1 = new javax.swing.JTextField();
        TF_Nacionalidad1 = new javax.swing.JTextField();
        JS_Edad1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TF_Contrato_E = new javax.swing.JTextField();
        TF_Copas = new javax.swing.JTextField();
        JB_AgregarE = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        JT_Entrenador = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        JL_ENTRE = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        JD_PredadoresFisico = new javax.swing.JDialog();
        TF_Nombre2 = new javax.swing.JTextField();
        TF_Apellido2 = new javax.swing.JTextField();
        TF_Nacionalidad2 = new javax.swing.JTextField();
        JS_Edad2 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TF_ID = new javax.swing.JTextField();
        TF_Contrato_PF = new javax.swing.JTextField();
        TF_Especial = new javax.swing.JTextField();
        TF_TituloD = new javax.swing.JTextField();
        JB_Preparador = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        JT_Prepardor = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        JL_PREPA = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        JD_Psicologos = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TF_Nombre3 = new javax.swing.JTextField();
        TF_Apellido3 = new javax.swing.JTextField();
        TF_Nacionalidad3 = new javax.swing.JTextField();
        JS_Edad3 = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TF_TituloU = new javax.swing.JTextField();
        TF_ID1 = new javax.swing.JTextField();
        TF_Especial1 = new javax.swing.JTextField();
        JB_Psicologo = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        JT_Psicologos = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        JL_PSICO = new javax.swing.JList<>();
        JB_APS = new javax.swing.JButton();
        JD_Modificar = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_Entrenadores = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_Jugadores = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Psicologos = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        Jl_Prepadores = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        JD_Arbol = new javax.swing.JDialog();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        POPMENU_CRUD = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        Listar_JUGADOR = new javax.swing.JMenuItem();
        Listar_ENTRENADOR = new javax.swing.JMenuItem();
        Listar_PREPADOR = new javax.swing.JMenuItem();
        Listar_PSICOLOGO = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Eliminar_JUGADOR = new javax.swing.JMenuItem();
        Eiminar_ENTRENADOR = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        M_AgregarMiem = new javax.swing.JMenu();
        MI_Jugador = new javax.swing.JMenuItem();
        MI_Entrenador = new javax.swing.JMenuItem();
        MI_PreparadorF = new javax.swing.JMenuItem();
        MI_Psicologos = new javax.swing.JMenuItem();
        M_Arbol = new javax.swing.JMenu();
        MI_Ver_A = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MI_Infrome = new javax.swing.JMenuItem();

        JD_Juga.setTitle("Agregar Jugadores");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nombre: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nacionalidad: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Edad: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Numero del Jugador: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad de años que dura su contrato: ");

        JB_AgregarJ.setText("Agregar Jugador al sistema");
        JB_AgregarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarJMouseClicked(evt);
            }
        });

        JT_Jugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Numero del Jugador", "Contrato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JT_Jugadores);

        jScrollPane12.setViewportView(JL_JUGA);

        JB_AJ.setText("Agergar Arbol");
        JB_AJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_JugaLayout = new javax.swing.GroupLayout(JD_Juga.getContentPane());
        JD_Juga.getContentPane().setLayout(JD_JugaLayout);
        JD_JugaLayout.setHorizontalGroup(
            JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_JugaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_JugaLayout.createSequentialGroup()
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JD_JugaLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TF_Num_J, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JD_JugaLayout.createSequentialGroup()
                                    .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(21, 21, 21)
                                    .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JS_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(JD_JugaLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_Contrato)))
                            .addGroup(JD_JugaLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(JB_AgregarJ)))
                        .addGap(56, 56, 56)
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_AJ, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        JD_JugaLayout.setVerticalGroup(
            JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_JugaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JD_JugaLayout.createSequentialGroup()
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TF_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JS_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_Num_J, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_JugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_AgregarJ)
                    .addComponent(JB_AJ))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Nacionalidad: ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Edad: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Nombre: ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Apellido:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Años de contrato como entrenador: ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Cantidad de copas: ");

        TF_Contrato_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Contrato_EActionPerformed(evt);
            }
        });

        JB_AgregarE.setText("Agregar Entrenador");
        JB_AgregarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarEMouseClicked(evt);
            }
        });

        JT_Entrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Años de contrato", "Cantidad de copas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(JT_Entrenador);

        jScrollPane13.setViewportView(JL_ENTRE);

        jButton7.setText("Agregar al Arbol");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_EntrenadoresLayout = new javax.swing.GroupLayout(JD_Entrenadores.getContentPane());
        JD_Entrenadores.getContentPane().setLayout(JD_EntrenadoresLayout);
        JD_EntrenadoresLayout.setHorizontalGroup(
            JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TF_Contrato_E, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JB_AgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF_Copas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(146, 146, 146)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(21, 21, 21)
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JS_Edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        JD_EntrenadoresLayout.setVerticalGroup(
            JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TF_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TF_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TF_Nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(JS_Edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_EntrenadoresLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TF_Contrato_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TF_Copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_EntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_AgregarE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Nombre: ");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Apellido:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Nacionalidad: ");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("ID: ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Edad: ");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Años de contrato: ");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Especialidad: ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Titulo como Doctor: ");

        JB_Preparador.setText("Agregar Doctor");
        JB_Preparador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_PreparadorMouseClicked(evt);
            }
        });

        JT_Prepardor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "ID", "Años de contrato", "Especialidad", "Ttitulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(JT_Prepardor);

        jScrollPane14.setViewportView(JL_PREPA);

        jButton6.setText("Agregar al Arbol");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_PredadoresFisicoLayout = new javax.swing.GroupLayout(JD_PredadoresFisico.getContentPane());
        JD_PredadoresFisico.getContentPane().setLayout(JD_PredadoresFisicoLayout);
        JD_PredadoresFisicoLayout.setHorizontalGroup(
            JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_TituloD, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(36, 36, 36)
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JS_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Nacionalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane14))
                            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Especial, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Contrato_PF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JB_Preparador, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                .addContainerGap())
        );
        JD_PredadoresFisicoLayout.setVerticalGroup(
            JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PredadoresFisicoLayout.createSequentialGroup()
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(TF_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TF_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TF_Nacionalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JS_Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(TF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TF_Contrato_PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(TF_Especial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(TF_TituloD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_PredadoresFisicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Preparador)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Nombre: ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Apellido:");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Nacionalidad: ");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Edad: ");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Titulo universitatrio: ");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("ID: ");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Especialidad: ");

        JB_Psicologo.setText("Agregar Psicologo");
        JB_Psicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_PsicologoMouseClicked(evt);
            }
        });

        JT_Psicologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Titulo", "ID", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(JT_Psicologos);

        jScrollPane15.setViewportView(JL_PSICO);

        JB_APS.setText("Agregar al Arbol");
        JB_APS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_APSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_PsicologosLayout = new javax.swing.GroupLayout(JD_Psicologos.getContentPane());
        JD_Psicologos.getContentPane().setLayout(JD_PsicologosLayout);
        JD_PsicologosLayout.setHorizontalGroup(
            JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PsicologosLayout.createSequentialGroup()
                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_Especial1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TF_TituloU, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(18, 18, 18)
                                        .addComponent(TF_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addGap(36, 36, 36)
                                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TF_Apellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JS_Edad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Nacionalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(JB_Psicologo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JB_APS, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        JD_PsicologosLayout.setVerticalGroup(
            JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_PsicologosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_PsicologosLayout.createSequentialGroup()
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(TF_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(TF_Apellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(TF_Nacionalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JS_Edad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(9, 9, 9)
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(TF_TituloU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(TF_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(TF_Especial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_PsicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Psicologo)
                    .addComponent(JB_APS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Jugadores:");

        jLabel8.setText("Entrenadores");

        jLabel9.setText("Preparadores Fiscos: ");

        jLabel10.setText("Psicologos: ");

        jScrollPane2.setViewportView(JL_Entrenadores);

        jScrollPane3.setViewportView(JL_Jugadores);

        jScrollPane4.setViewportView(JL_Psicologos);

        jScrollPane5.setViewportView(Jl_Prepadores);

        javax.swing.GroupLayout JD_ModificarLayout = new javax.swing.GroupLayout(JD_Modificar.getContentPane());
        JD_Modificar.getContentPane().setLayout(JD_ModificarLayout);
        JD_ModificarLayout.setHorizontalGroup(
            JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(298, 298, 298))
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(274, 274, 274)
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_ModificarLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 83, Short.MAX_VALUE))))
            .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JD_ModificarLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );
        JD_ModificarLayout.setVerticalGroup(
            JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(JD_ModificarLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(JD_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JD_ModificarLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addGap(243, 243, 243)))
        );

        jLabel15.setText("jLabel15");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable2);

        jTextField3.setText("jTextField3");

        jButton5.setText("jButton5");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipo");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane11.setViewportView(jTree1);

        javax.swing.GroupLayout JD_ArbolLayout = new javax.swing.GroupLayout(JD_Arbol.getContentPane());
        JD_Arbol.getContentPane().setLayout(JD_ArbolLayout);
        JD_ArbolLayout.setHorizontalGroup(
            JD_ArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        JD_ArbolLayout.setVerticalGroup(
            JD_ArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu2.setText("Listar\n");

        Listar_JUGADOR.setText("jMenuItem1");
        jMenu2.add(Listar_JUGADOR);

        Listar_ENTRENADOR.setText("jMenuItem2");
        jMenu2.add(Listar_ENTRENADOR);

        Listar_PREPADOR.setText("jMenuItem3");
        jMenu2.add(Listar_PREPADOR);

        Listar_PSICOLOGO.setText("jMenuItem4");
        jMenu2.add(Listar_PSICOLOGO);

        POPMENU_CRUD.add(jMenu2);

        jMenu3.setText("Eliminar");

        Eliminar_JUGADOR.setText("jMenuItem1");
        jMenu3.add(Eliminar_JUGADOR);

        Eiminar_ENTRENADOR.setText("jMenuItem2");
        jMenu3.add(Eiminar_ENTRENADOR);

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu3.add(jMenuItem4);

        POPMENU_CRUD.add(jMenu3);

        Modificar.setText("Modificar");
        POPMENU_CRUD.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Agregar Jugadores");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Agregar Entrenadores");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("Agregar Preparadores");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Agregar Psicologos");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton4);

        M_AgregarMiem.setText("Agrergar Miembros");

        MI_Jugador.setText("Crear Jugador");
        MI_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_JugadorActionPerformed(evt);
            }
        });
        M_AgregarMiem.add(MI_Jugador);

        MI_Entrenador.setText("Crear Entrenador");
        MI_Entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_EntrenadorActionPerformed(evt);
            }
        });
        M_AgregarMiem.add(MI_Entrenador);

        MI_PreparadorF.setText("Crear Preparador Fisico");
        MI_PreparadorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_PreparadorFActionPerformed(evt);
            }
        });
        M_AgregarMiem.add(MI_PreparadorF);

        MI_Psicologos.setText("Crear Psicologo");
        MI_Psicologos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_PsicologosActionPerformed(evt);
            }
        });
        M_AgregarMiem.add(MI_Psicologos);

        jMenuBar1.add(M_AgregarMiem);

        M_Arbol.setText("Ver Arbol");

        MI_Ver_A.setText("Ver Arbol");
        M_Arbol.add(MI_Ver_A);

        jMenuBar1.add(M_Arbol);

        jMenu1.setText("Informe de Partidos");

        MI_Infrome.setText("Informe de Partidos");
        jMenu1.add(MI_Infrome);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AgregarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarJMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel) JL_Jugadores.getModel();
        int num_j=Integer.parseInt(TF_Num_J.getText());
        int contra=Integer.parseInt(TF_Contrato.getText());
        modelo.addElement(new Jugadores(num_j,contra,TF_Nombre.getText(),TF_Apellido.getText(),TF_Nacionalidad.getText(),(Integer)JS_Edad.getValue()));
        Jugadores j=new Jugadores(num_j,contra,TF_Nombre.getText(),TF_Apellido.getText(),TF_Nacionalidad.getText(),(Integer)JS_Edad.getValue());
        Object newrow[] ={j.getNombre(),j.getApellido(),j.getNacionalidad(),j.getEdad(),j.getNumero_de_j(),j.getContrato()};
        DefaultTableModel m=(DefaultTableModel) JT_Jugadores.getModel();
        m.addRow(newrow);
        JL_JUGA.setModel(modelo);
        JL_Jugadores.setModel(modelo);
        JT_Jugadores.setModel(m);
        TF_Nombre.setText("");
        TF_Apellido.setText("");
        TF_Nacionalidad.setText("");
        JS_Edad.setValue(0);
        TF_Num_J.setText("");
        TF_Contrato.setText("");
    }//GEN-LAST:event_JB_AgregarJMouseClicked

    private void TF_Contrato_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Contrato_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Contrato_EActionPerformed

    private void JB_AgregarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarEMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel) JL_Entrenadores.getModel();
        int copas=Integer.parseInt(TF_Copas.getText());
        int contra=Integer.parseInt(TF_Contrato_E.getText());
        modelo.addElement(new Entrenadores(contra,copas,TF_Nombre1.getText(),TF_Apellido1.getText(),TF_Nacionalidad1.getText(),(Integer)JS_Edad1.getValue()));
        Entrenadores j=new Entrenadores(contra,copas,TF_Nombre1.getText(),TF_Apellido1.getText(),TF_Nacionalidad1.getText(),(Integer)JS_Edad1.getValue());
        Object newrow[] ={j.getNombre(),j.getApellido(),j.getNacionalidad(),j.getEdad(),j.getContrato(),j.getCantidad_c()};
        DefaultTableModel m=(DefaultTableModel) JT_Entrenador.getModel();
        m.addRow(newrow);
        JL_ENTRE.setModel(modelo);
        JL_Entrenadores.setModel(modelo);
        JT_Entrenador.setModel(m);
        TF_Nombre1.setText("");
        TF_Apellido1.setText("");
        TF_Nacionalidad1.setText("");
        JS_Edad1.setValue(0);
        TF_Contrato_E.setText("");
        TF_Copas.setText("");
    }//GEN-LAST:event_JB_AgregarEMouseClicked

    private void JB_PreparadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_PreparadorMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel) Jl_Prepadores.getModel();
        int contra=Integer.parseInt(TF_Contrato_PF.getText());
        modelo.addElement(new PreparadoresFisico(TF_ID.getText(),contra,TF_Especial.getText(),TF_TituloD.getText(),TF_Nombre2.getText(),TF_Apellido2.getText(),TF_Nacionalidad2.getText(),(Integer)JS_Edad2.getValue()));
        PreparadoresFisico j=new PreparadoresFisico(TF_ID.getText(),contra,TF_Especial.getText(),TF_TituloD.getText(),TF_Nombre2.getText(),TF_Apellido2.getText(),TF_Nacionalidad2.getText(),(Integer)JS_Edad2.getValue());
        Object newrow[] ={j.getNombre(),j.getApellido(),j.getNacionalidad(),j.getEdad(),j.getID(),j.getContrato(),j.getEspecialidad(),j.getTitulo()};
        DefaultTableModel m=(DefaultTableModel) JT_Entrenador.getModel();
        m.addRow(newrow);
        JL_PREPA.setModel(modelo);
        Jl_Prepadores.setModel(modelo);
        JT_Prepardor.setModel(m);
        TF_Nombre2.setText("");
        TF_Apellido2.setText("");
        TF_Nacionalidad2.setText("");
        JS_Edad2.setValue(0);
        TF_Contrato_PF.setText("");
        TF_ID.setText("");
        TF_Especial.setText("");
        TF_TituloD.setText("");
    }//GEN-LAST:event_JB_PreparadorMouseClicked

    private void JB_PsicologoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_PsicologoMouseClicked
        // TODO add your handling code here:
         DefaultListModel modelo=(DefaultListModel) JL_Psicologos.getModel();
        
        modelo.addElement(new Psicologos(TF_TituloU.getText(),TF_ID1.getText(),TF_Especial1.getText(),TF_Nombre3.getText(),TF_Apellido3.getText(),TF_Nacionalidad3.getText(),(Integer)JS_Edad3.getValue()));
        Psicologos j=new Psicologos(TF_TituloU.getText(),TF_ID1.getText(),TF_Especial1.getText(),TF_Nombre3.getText(),TF_Apellido3.getText(),TF_Nacionalidad3.getText(),(Integer)JS_Edad3.getValue());
        Object newrow[] ={j.getNombre(),j.getApellido(),j.getNacionalidad(),j.getEdad(),j.getTitulo(),j.getID(),j.getEspecialidad()};
        DefaultTableModel m=(DefaultTableModel) JT_Entrenador.getModel();
        m.addRow(newrow);
        JL_PSICO.setModel(modelo);
        JL_Psicologos.setModel(modelo);
        JT_Psicologos.setModel(m);
        TF_Nombre3.setText("");
        TF_Apellido3.setText("");
        TF_Nacionalidad3.setText("");
        JS_Edad3.setValue(0);
        TF_ID1.setText("");
        TF_Especial1.setText("");
        TF_Especial.setText("");
    }//GEN-LAST:event_JB_PsicologoMouseClicked

    private void MI_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_JugadorActionPerformed
        // TODO add your handling code here:
        JDJuga();
    }//GEN-LAST:event_MI_JugadorActionPerformed

    private void MI_EntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_EntrenadorActionPerformed
        // TODO add your handling code here:
        JDEntre();
    }//GEN-LAST:event_MI_EntrenadorActionPerformed

    private void MI_PreparadorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_PreparadorFActionPerformed
        // TODO add your handling code here:
        JDPrepa();
    }//GEN-LAST:event_MI_PreparadorFActionPerformed

    private void MI_PsicologosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_PsicologosActionPerformed
        // TODO add your handling code here:
        JDPsico();
    }//GEN-LAST:event_MI_PsicologosActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JDJuga();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JDEntre();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        JDPrepa();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        JDPsico();
    }//GEN-LAST:event_jButton4MouseClicked

    private void JB_AJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AJMouseClicked
        // TODO add your handling code here:
        try {
            if (JL_JUGA.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) JL_JUGA.getModel();
                int num_cami;
                String Nombre;
                String Apellido;
                int Edad;
                String Naciona;
                int contra;
                num_cami= (((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getNumero_de_j());
                Nombre = ((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getNombre();
                Apellido = ((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getApellido();
                Edad = ((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getEdad();
                Naciona = ((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getNacionalidad();
                contra=((Jugadores) modeloLISTA.get(JL_JUGA.getSelectedIndex())).getContrato();
                int centinela = -1;
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().
                            equals(Nombre)) {
                        
                        DefaultMutableTreeNode p
                                = new DefaultMutableTreeNode(
                                        new Jugadores(num_cami,contra, Nombre, Apellido, Naciona, Edad));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }//if
                }//fin del for
                if (centinela == -1) {
                    DefaultMutableTreeNode n
                            = new DefaultMutableTreeNode("Jugadores");
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new  Jugadores(num_cami,contra, Nombre, Apellido, Naciona, Edad));
                    n.add(p);
                    raiz.add(n);
                }//if else
                modeloARBOL.reload();
                JOptionPane.showMessageDialog(this, "Se ha agregado al arbol");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }//if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Inesperado");
        }//try catch
    }//GEN-LAST:event_JB_AJMouseClicked

    private void JB_APSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_APSMouseClicked
        // TODO add your handling code here:
        try {
            if (JL_PSICO.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) JL_PSICO.getModel();
                String id;
                String Nombre;
                String Apellido;
                int Edad;
                String Naciona;
                String especial;
                String tituloU;
                id = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getID();
                Nombre = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getNombre();
                Apellido = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getApellido();
                Edad = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getEdad();
                Naciona = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getNacionalidad();
                 especial = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getEspecialidad();
                tituloU = ((Psicologos) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getTitulo();
                int centinela = -1;
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().
                            equals(Nombre)) {
                        
                        DefaultMutableTreeNode p
                                = new DefaultMutableTreeNode(
                                        new Psicologos(tituloU, id, especial, Nombre, Apellido, Naciona, Edad));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }//if
                }//fin del for
                if (centinela == -1) {
                    DefaultMutableTreeNode n
                            = new DefaultMutableTreeNode("Psicologo");
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new  Psicologos(tituloU, id, especial, Nombre, Apellido, Naciona, Edad));
                    n.add(p);
                    raiz.add(n);
                }//if else
                modeloARBOL.reload();
                JOptionPane.showMessageDialog(this, "Se ha agregado al arbol");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }//if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Inesperado");
        }//try catch
    }//GEN-LAST:event_JB_APSMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
          try {
            if (JL_PREPA.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) JL_PREPA.getModel();
                String id;
                String Nombre;
                String Apellido;
                int Edad;
                String Naciona;
                String especial;
                String tituloD;
                int contra;
                id = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getID();
                Nombre = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getNombre();
                Apellido = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getApellido();
                Edad = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getEdad();
                Naciona = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getNacionalidad();
                 especial = ((PreparadoresFisico) modeloLISTA.get(JL_PREPA.getSelectedIndex())).getEspecialidad();
                tituloD = ((PreparadoresFisico) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getTitulo();
                contra=((PreparadoresFisico) modeloLISTA.get(JL_PSICO.getSelectedIndex())).getContrato();
                int centinela = -1;
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().
                            equals(Nombre)) {
                        
                        DefaultMutableTreeNode p
                                = new DefaultMutableTreeNode(
                                        new PreparadoresFisico( id,contra, especial,tituloD, Nombre, Apellido, Naciona, Edad));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }//if
                }//fin del for
                if (centinela == -1) {
                    DefaultMutableTreeNode n
                            = new DefaultMutableTreeNode("Preparador Fisico");
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new PreparadoresFisico( id,contra, especial,tituloD, Nombre, Apellido, Naciona, Edad));
                    n.add(p);
                    raiz.add(n);
                }//if else
                modeloARBOL.reload();
                JOptionPane.showMessageDialog(this, "Se ha agregado al arbol");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }//if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Inesperado");
            e.printStackTrace();
        }//try catch
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
          try {
            if (JL_ENTRE.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) jTree1.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) JL_ENTRE.getModel();
                int copas;
                String Nombre;
                String Apellido;
                int Edad;
                String Naciona;
                int contra;
                copas= (((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getCantidad_c());
                Nombre = ((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getNombre();
                Apellido = ((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getApellido();
                Edad = ((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getEdad();
                Naciona = ((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getNacionalidad();
                contra=((Entrenadores) modeloLISTA.get(JL_ENTRE.getSelectedIndex())).getContrato();
                int centinela = -1;
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().
                            equals(Nombre)) {
                        
                        DefaultMutableTreeNode p
                                = new DefaultMutableTreeNode(
                                        new Entrenadores(contra,copas, Nombre, Apellido, Naciona, Edad));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        centinela = 1;
                    }//if
                }//fin del for
                if (centinela == -1) {
                    DefaultMutableTreeNode n
                            = new DefaultMutableTreeNode("Entrenadores");
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new  Entrenadores(contra,copas, Nombre, Apellido, Naciona, Edad));
                    n.add(p);
                    raiz.add(n);
                }//if else
                modeloARBOL.reload();
                JOptionPane.showMessageDialog(this, "Se ha agregado al arbol");
            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }//if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Inesperado");
        }//try catch
    }//GEN-LAST:event_jButton7MouseClicked
public void JDJuga(){
    JD_Juga.pack();
        JD_Juga.setModal(true);
        JD_Juga.setLocationRelativeTo(this);
        JD_Juga.setVisible(true);
}
public void JDEntre(){
    JD_Entrenadores.pack();
        JD_Entrenadores.setModal(true);
        JD_Entrenadores.setLocationRelativeTo(this);
        JD_Entrenadores.setVisible(true);
}
public void JDPrepa(){
    JD_PredadoresFisico.pack();
    JD_PredadoresFisico.setModal(true);
        JD_PredadoresFisico.setLocationRelativeTo(this);
        JD_PredadoresFisico.setVisible(true);
}
public void JDPsico(){
     JD_Psicologos.pack();
    JD_Psicologos.setModal(true);
        JD_Psicologos.setLocationRelativeTo(this);
        JD_Psicologos.setVisible(true);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Lab5P2_CarlosSanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Lab5P2_CarlosSanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Lab5P2_CarlosSanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Lab5P2_CarlosSanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Lab5P2_CarlosSanabria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eiminar_ENTRENADOR;
    private javax.swing.JMenuItem Eliminar_JUGADOR;
    private javax.swing.JButton JB_AJ;
    private javax.swing.JButton JB_APS;
    private javax.swing.JButton JB_AgregarE;
    private javax.swing.JButton JB_AgregarJ;
    private javax.swing.JButton JB_Preparador;
    private javax.swing.JButton JB_Psicologo;
    private javax.swing.JDialog JD_Arbol;
    private javax.swing.JDialog JD_Entrenadores;
    private javax.swing.JDialog JD_Juga;
    private javax.swing.JDialog JD_Modificar;
    private javax.swing.JDialog JD_PredadoresFisico;
    private javax.swing.JDialog JD_Psicologos;
    private javax.swing.JList<String> JL_ENTRE;
    private javax.swing.JList<String> JL_Entrenadores;
    private javax.swing.JList<String> JL_JUGA;
    private javax.swing.JList<String> JL_Jugadores;
    private javax.swing.JList<String> JL_PREPA;
    private javax.swing.JList<String> JL_PSICO;
    private javax.swing.JList<String> JL_Psicologos;
    private javax.swing.JSpinner JS_Edad;
    private javax.swing.JSpinner JS_Edad1;
    private javax.swing.JSpinner JS_Edad2;
    private javax.swing.JSpinner JS_Edad3;
    private javax.swing.JTable JT_Entrenador;
    private javax.swing.JTable JT_Jugadores;
    private javax.swing.JTable JT_Prepardor;
    private javax.swing.JTable JT_Psicologos;
    private javax.swing.JList<String> Jl_Prepadores;
    private javax.swing.JMenuItem Listar_ENTRENADOR;
    private javax.swing.JMenuItem Listar_JUGADOR;
    private javax.swing.JMenuItem Listar_PREPADOR;
    private javax.swing.JMenuItem Listar_PSICOLOGO;
    private javax.swing.JMenuItem MI_Entrenador;
    private javax.swing.JMenuItem MI_Infrome;
    private javax.swing.JMenuItem MI_Jugador;
    private javax.swing.JMenuItem MI_PreparadorF;
    private javax.swing.JMenuItem MI_Psicologos;
    private javax.swing.JMenuItem MI_Ver_A;
    private javax.swing.JMenu M_AgregarMiem;
    private javax.swing.JMenu M_Arbol;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JPopupMenu POPMENU_CRUD;
    private javax.swing.JTextField TF_Apellido;
    private javax.swing.JTextField TF_Apellido1;
    private javax.swing.JTextField TF_Apellido2;
    private javax.swing.JTextField TF_Apellido3;
    private javax.swing.JTextField TF_Contrato;
    private javax.swing.JTextField TF_Contrato_E;
    private javax.swing.JTextField TF_Contrato_PF;
    private javax.swing.JTextField TF_Copas;
    private javax.swing.JTextField TF_Especial;
    private javax.swing.JTextField TF_Especial1;
    private javax.swing.JTextField TF_ID;
    private javax.swing.JTextField TF_ID1;
    private javax.swing.JTextField TF_Nacionalidad;
    private javax.swing.JTextField TF_Nacionalidad1;
    private javax.swing.JTextField TF_Nacionalidad2;
    private javax.swing.JTextField TF_Nacionalidad3;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JTextField TF_Nombre1;
    private javax.swing.JTextField TF_Nombre2;
    private javax.swing.JTextField TF_Nombre3;
    private javax.swing.JTextField TF_Num_J;
    private javax.swing.JTextField TF_TituloD;
    private javax.swing.JTextField TF_TituloU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
